"use strict";
const fs = require("fs");
const path = require("path");
const jsonName = process.argv[2];
const retire = process.argv.slice(3);
if (!jsonName) throw new Error("usage: _merge_song.js <json> [retire-id...]");
const lib = path.join(__dirname, "..", "library");
const incoming = JSON.parse(fs.readFileSync(path.join(lib, jsonName), "utf8")).library[0];
const jsPath = path.join(lib, "imported-songs.js");
const text = fs.readFileSync(jsPath, "utf8");
const match = text.match(/window\.koufengqinImportedSongs\s*=\s*(\[[\s\S]*\])\s*;\s*$/);
if (!match) throw new Error("cannot parse imported-songs.js");
const drop = new Set([incoming.id, ...retire]);
const songs = JSON.parse(match[1]).filter((song) => !drop.has(song.id));
songs.unshift(incoming);
fs.writeFileSync(jsPath, `window.koufengqinImportedSongs = ${JSON.stringify(songs)};\n`, "utf8");
const last = incoming.events[incoming.events.length - 1];
console.log(`${incoming.title} n=${incoming.events.length} dur=${(last.t + last.d).toFixed(1)}`);
for (const song of songs) console.log(`${song.id}\t${song.title}`);
